-- Resposta Exercício 1.1: inserindo Dados com INSERT na tabela PXC.EXTRATO
INSERT INTO PXC.EXTRATO (ID, NUMERO_CONTA, NOME_TITULAR) VALUES (1, 915201, 'Rory Fry');
INSERT INTO PXC.EXTRATO (ID, NUMERO_CONTA, NOME_TITULAR) VALUES (2, 67890, 'Amari Black');
