-- Gabarito: Exercício 1 (CREATE TABLE)
-- 1.3 Criação da tabela REGISTRO com chaves estrangeiras
CREATE TABLE REGISTRO (
    ID INTEGER PRIMARY KEY,
    VALOR INTEGER,
    ID_TIPO INTEGER,
    ID_EXTRATO INTEGER,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_REGISTRO(ID),
    FOREIGN KEY (ID_EXTRATO) REFERENCES EXTRATO(ID)
);
